GET http://127.0.0.1:5000/ledger/buckets

###
POST http://127.0.0.1:5000/ledger/buckets
Content-Type: application/x-www-form-urlencoded

identifier=test

###
GET http://127.0.0.1:5000/ledger/buckets/sum?loanId=123&bucketids=accounts-receivable-interest,loan-commitment-liability
Content-Type: application/json

###
GET http://127.0.0.1:5000/ledger/entries?loanId=1

###